Algoritmo "sequencial"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2024
Var
// Seção de Declarações das variáveis 
n1, n2, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe n1: ")
leia(n1)

escreva("informe n2: ")
leia(n2)

soma <- n1 + n2
escreva(" Soma = ", soma)

Fimalgoritmo