Algoritmo "Uso_de Funcao_predefinida"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/05/2024
Var
// Seção de Declarações das variáveis 
numero, raiz: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um número: ")
 leia(numero)
 raiz <- Raizq(numero)
 escreva("A raiz quadrada do número digitado é: ", raiz)

Fimalgoritmo